const fs = require('fs');
const path = require('path');

console.log('🛠️  Setting up Frontend environment...');

const content = `
# Local Development Environment
# Generated by setup-env.js

VITE_API_URL=http://localhost:3010
VITE_ENV=development
VITE_APP_NAME="Ataraxia Health"
# Add other public variables here
`.trim();

const targetPath = path.join(__dirname, '../.env.local');
fs.writeFileSync(targetPath, content);
console.log(`✅ Created .env.local at ${targetPath}`);

console.log('\n🎉 Frontend setup complete! Run: npm run dev');
