#!/bin/bash

# Cleanup Script - Removes Outdated Documentation Files
# Only keeps the essential, up-to-date documentation

echo "🧹 Cleaning up outdated documentation files..."
echo ""

# Keep these essential files:
KEEP_FILES=(
  "START_HERE_AUTHORITATIVE_GUIDE.md"
  "API_INTEGRATION_GUIDE.md"
  "SECURITY_ARCHITECTURE.md"
  "README.md"
  "Attributions.md"
  "firestore.rules"
  "storage.rules"
  "test-backend-connection.sh"
  "test-appointment-flow.sh"
  "cleanup-docs.sh"
  "cleanup-old-docs.sh"
)

# Count files to be removed
COUNT=0

# List of documentation files to remove (outdated/redundant)
FILES_TO_REMOVE=(
  "ACTION_REQUIRED_RESTART.md"
  "ACTUAL_SOLUTION.md"
  "AFTER_RESTART_EXPECT.md"
  "API_ENDPOINTS_EXPLAINED.md"
  "API_QUICK_REFERENCE.md"
  "BACKEND_CONFIG.md"
  "BACKEND_ENDPOINT_SPEC.md"
  "BACKEND_URLS.md"
  "BACKEND_URL_CORRECTED.md"
  "BACKEND_URL_FIXED.md"
  "BACKEND_URL_UPDATE.md"
  "BEARER_TOKEN_DEBUG.md"
  "BEARER_TOKEN_FLOW.md"
  "CLICK_HERE_TO_TEST.md"
  "COMPLETE_INTEGRATION_SUMMARY.md"
  "COMPLETE_SETUP_SUMMARY.md"
  "COMPLETE_SOLUTION_SUMMARY.md"
  "CONFIGURATION_FIXED.md"
  "CONFIG_GUIDE.md"
  "CONSOLE_OUTPUT_GUIDE.md"
  "CORRECT_JWT_FLOW.md"
  "CORRECT_VIDEO_TEST_GUIDE.md"
  "CORS_ERROR_FIXED.md"
  "CORS_FIXED_FINAL.md"
  "CORS_FIXED_SUMMARY.md"
  "CORS_FIXED_USE_PROXY.md"
  "CORS_FIX_FOR_LOCALHOST.md"
  "CORS_ISSUE_AND_SOLUTION.md"
  "CORS_SETUP_BOTH.md"
  "CREATE_SESSION_TEST_GUIDE.md"
  "DIRECT_VIDEO_TEST_GUIDE.md"
  "DOCUMENTATION_INDEX.md"
  "DO_THIS_NOW.md"
  "DO_THIS_RIGHT_NOW.md"
  "ERRORS_FIXED.md"
  "ERRORS_FIXED_FINAL.md"
  "ERRORS_SILENCED.md"
  "ERROR_DIAGNOSTIC_GUIDE.md"
  "ERROR_FIXED_GUIDE.md"
  "ERROR_FIX_SUMMARY.md"
  "EVERYTHING_FIXED_README.md"
  "EXACT_BACKEND_API_FLOW.md"
  "FINAL_FIX_SUMMARY.md"
  "FIREBASE_FIX_QUICK.md"
  "FIRESTORE_RULES_DEPLOY.md"
  "FIRESTORE_RULES_EXPLAINED.md"
  "FIX_CORS_NOW.md"
  "FIX_FAILED_TO_FETCH.md"
  "FIX_INVALID_SIGNATURE_NOW.md"
  "FIX_IN_2_STEPS.md"
  "FIX_SUMMARY_SIMPLE.md"
  "HOW_TO_TEST_VIDEO_CALLING.md"
  "IFRAME_VS_EXTERNAL_API.md"
  "INTEGRATION_SUMMARY.md"
  "INVALID_SIGNATURE_FIX.md"
  "JITSI_EXTERNAL_API_CONFIRMED.md"
  "JITSI_EXTERNAL_API_GUIDE.md"
  "JITSI_QUICK_START.md"
  "JITSI_SERVER_CORS_CONFIG.md"
  "JITSI_SETUP.md"
  "JITSI_STATUS.md"
  "JITSI_TEST_GUIDE.md"
  "JWT_SIGNING_ISSUE_EXPLAINED.md"
  "LOCALHOST_PORT_EXPLAINED.md"
  "MASTER_FIX_GUIDE.md"
  "MOCK_MODE_REMOVED.md"
  "MODERATOR_AUTO_JOIN_FIXED.md"
  "PRODUCTION_VIDEO_TEST_GUIDE.md"
  "QUICK_CONFIG.md"
  "QUICK_FIX.md"
  "QUICK_FIX_SUMMARY.md"
  "QUICK_VIDEO_TEST.md"
  "README_SOLUTION.md"
  "READY_TO_TEST.md"
  "READY_TO_TEST_NOW.md"
  "READ_ME_FIRST.md"
  "RESTART_AND_TEST.md"
  "RESTART_DEV_SERVER_NOW.md"
  "SEAMLESS_VIDEO_TEST_COMPLETE.md"
  "SECURE_VIDEO_TEST_GUIDE.md"
  "SECURITY_IMPLEMENTATION_GUIDE.md"
  "SECURITY_INTEGRATION_COMPLETE.md"
  "SIMPLE_TEST_GUIDE.md"
  "START.md"
  "START_HERE.md"
  "START_HERE_CLEAN.md"
  "START_HERE_NOW.md"
  "START_HERE_VIDEO_TEST.md"
  "START_VIDEO_TEST.md"
  "TESTING_READY.md"
  "TESTING_VIDEO_CALLS.md"
  "TEST_APPOINTMENT_SCRIPT.md"
  "TEST_NOW.md"
  "UPDATED_FOR_YOUR_API.md"
  "USER_CREDENTIALS_FOR_BACKEND.md"
  "USE_SECURE_VIDEO_TEST.md"
  "VIDEO_CALLING_COMPLETE.md"
  "VIDEO_CALLING_READY.md"
  "VIDEO_DOCS_INDEX.md"
  "VIDEO_TEST_QUICKSTART.md"
  "VIDEO_TEST_READY.md"
  "VISUAL_DEPLOYMENT_GUIDE.md"
  "VISUAL_FIX_SUMMARY.md"
  "WHERE_YOUR_APP_RUNS.md"
)

echo "📋 Files to be removed: ${#FILES_TO_REMOVE[@]}"
echo ""

# Remove each file
for file in "${FILES_TO_REMOVE[@]}"; do
  if [ -f "$file" ]; then
    rm "$file"
    echo "  ✅ Removed: $file"
    ((COUNT++))
  fi
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Cleanup complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 Summary:"
echo "  • Files removed: $COUNT"
echo "  • Essential docs kept:"
echo "    - START_HERE_AUTHORITATIVE_GUIDE.md (Main guide)"
echo "    - API_INTEGRATION_GUIDE.md (API reference)"
echo "    - SECURITY_ARCHITECTURE.md (Security docs)"
echo "    - README.md (Project readme)"
echo "    - readme/ directory (Additional guides)"
echo ""
echo "🎯 Next steps:"
echo "  1. Read START_HERE_AUTHORITATIVE_GUIDE.md"
echo "  2. Run: ./test-backend-connection.sh"
echo "  3. Test your app: npm run dev"
echo ""
